### PR TITLE
CLAP: implement request_callback for Qt 5.0+

### PR DESCRIPTION
**Pull request by ahigerd**
The previous PR used a technique introduced in Qt 5.10, but since @rncbc wants to support Qt 5.9, this one works in 5.4 and higher. (I think I might like it slightly better anyway.)

### CODE REVIEW

**Comment by ahigerd** [comment]
Oh. Crap. Turns out this doesn't work after all -- my plugin was triggering this on the main thread already by mistake.

**Comment by ahigerd** [comment]
Okay, used a Qt 5.0+-compatible technique instead.

**Comment by rncbc** [comment]
oh please don't ... I believe it's pretty awesome asis now; old systems that still hang on qt5 < 5.10 may not cope to clap plugins anyway, so why bother? ;-)

**Comment by ahigerd** [comment]
I already updated this PR to fix it! You can reject it if the technique is too ugly for you, but it works.

**Comment by ahigerd** [comment]
Okay, it's too ugly. :P

**Pull request closed without merging**
