### PR TITLE
ignore snap while ALT is pressed

### PR DESCRIPTION
**Pull request by yosbelms**
#253 using ALT modifier

### CODE REVIEW

**Comment by rncbc** [comment]
This is a little too much cumbersome, in my opinion...

I believe it's rather better and an readyly solution would be about assigning a keyboard shortcut (Help > Shortcuts...) to View > Snap > None (eg. Ctrl+0) and a few others to your favorite grid snap-to-beat setting (eg. View > Snap > Beat = Ctrl+1; View > View > Snap > Beat/_N_ = Ctrl+_N_).

Both in the main tracks window _and_ on the MIDI clip editor.

Thanks anyway.

**Comment by yosbelms** [comment]
This is usability in may opinion. Actually this is a feature that you can find on Garage Band and Fruity Loops.

I should not be necessary if Qtractor provide a clip editor, where you could edit the clip with precission. But the only way (AFAIK) that Qtractor offers is move clip and split.

Although, both (clip editor, and precision drag) can live together I it was the case.

**Comment by userabc123xyz** [comment]
I like your idea, yosbelms

**Comment by oldcastlehq** [comment]
It has my vote too, because are the little things that make a difference :-)

**Comment by rncbc** [comment]
merged as https://github.com/rncbc/qtractor/commit/6ebc5a2 on [develop](https://github.com/rncbc/qtractor/tree/develop) branch.

please test && tell

**Pull request closed without merging**
