### PR TITLE
Added cmake uninstall target.

### PR DESCRIPTION
**Pull request by tcrass**
According to https://gitlab.kitware.com/cmake/community/-/wikis/FAQ#can-i-do-make-uninstall-with-cmake

### CODE REVIEW

**Comment by rncbc** [comment]
wonder whether this is really necessary :) you can always run qtractor from the cmake build folder (eg. `build/src/qtractor`), there's no real need to install it permanently as is only necessary for packaging, which have their own uninstall procedures that often never rely on any upstream uninstall target ;)

thanks anyway

**Comment by tcrass** [comment]
> wonder whether this is really necessary :) you can always run qtractor from the cmake build folder (eg. `build/src/qtractor`), there's no real need to install it permanently as it's only necessary for packaging, which have their own uninstall procedures that often never rely on any upstream uninstall target ;)

I did in fact install a local qtractor build on various PCs in our household (yes, my kids are using qtractor, too, and I want them to be able to launch the application through the launcher menu :) in order to circumvent [issue ](https://github.com/rncbc/qtractor/issues/357), so it would be nice if it was possible to easily uninstall it once the fix has made it into an official package.

And more generally (maybe for aesthetic reasons ;) if there's an "install" option I just expect an "uninstall" option to be also available.

Cheers --
Torsten

**Comment by rncbc** [comment]
so you're free to use your patch yourself, I guess

otoh. the latest builds from yours truly CI/CD upstream is available from the [repos](https://www.rncbc.org/drupal/node/2145)
AppImages included: here's a direct link to the (always) latest snapshot:
https://download.opensuse.org/repositories/home:/rncbc:/apps/AppImage/qtractor-latest-x86_64.AppImage

byee

**Comment by tcrass** [comment]
> so you're free to use your patch yourself, I guess

Well then... so be it!

> otoh. the latest builds from yours truly CI/CD upstream is available from these [repos](https://www.rncbc.org/drupal/node/2145); AppImages included: here's a direct link to the (always) latest snapshot: https://download.opensuse.org/repositories/home:/rncbc:/apps/AppImage/qtractor-latest-x86_64.AppImage

Good to know, thanks!

Cheers --
Torsten

**Pull request closed without merging**
