### PR TITLE
Proposal Track Auto BackgroundColor

### PR DESCRIPTION
**Pull request by G3N-es**
prppuesta_auto_color fondo segun principal

90% of the time we want the color of the track and the background of the clip to be the same tone.
It is true that there is a 10% in which it is useful to have the option to differentiate them.

This simple box solves it.

~~The code is fully functional~~, however be careful with the .ui
As you know, Qt Designer does not respect the original code and changes things without me being able to control it.
Also, I'm sure that if you decide to include this feature, you will find a more elegant place to host the check.
I still don't understand the visual tools of Designer.

The proposal is made for your consideration.

### CODE REVIEW

**Comment by G3N-es** [comment]
I didn't check it well, the code only half works :S

**Comment by G3N-es** [comment]
It works now, sorry for the rush.

**Comment by G3N-es** [comment]
It is a pleasure to see how a professional like you creates code.
Elegant, readable, solid and scalable.
I was also thinking that it would be necessary to save the state in options, and I see with surprise that you had already foreseen it. :-)

Thank you very much Rui for implementing my request.

**Comment by rncbc** [comment]
you're welcome; in the meantime I've just merged master into G3N-es-x branch. thanks

**Pull request merged**
