### PR TITLE
Update French translation for 0.9.35

### PR DESCRIPTION
**Pull request by trebmuh**

### CODE REVIEW

**Comment by rncbc** [comment]
I wonder if keyboard shortcuts are translatable... the case here: "Right" means the right-arrow key; does it translate to "Droite" in the FR environment? I don't think so

**Comment by trebmuh** [comment]
Thanks for taking care Rui.
Yes it does, "right arrow" (EN) translates into "flèche de droite" in French.
_(for info, "left arrow" (EN) would translates into "flèche de gauche" in French)_

**Comment by rncbc** [comment]
I'm in doubt that Qt does the translation at all (cf. Help / Shortcuts...) : whether "Droite" means "Right" for the french pc-keyboard right-arrow key...

on all my testings here, with LANG/LC_ALL=fr.utf-8, it doesn't. "Right" is the only way :)

**Comment by trebmuh** [comment]
OK, I get you now. Thanks for explaining it more precisely to me.
I've reversed the translation then.

Wouldn't that be a good idea to make this string untranslatable? Or to put a comment in the translation files that link to this very discussion?

Thanks  again.

**Comment by rncbc** [comment]
'do not translate' comments added in f347263

thanks

**Comment by trebmuh** [comment]
Thank you very much Rui.

**Pull request merged**
