### PR TITLE
Make qtractorMidiManager::deleteAudioOutputBus thread safe

### PR DESCRIPTION
**Pull request by schnitzeltony**
This is the crasher seen often during debug.

Signed-off-by: Andreas Müller <schnitzeltony@gmail.com>

### CODE REVIEW

**Comment by rncbc** [comment]
sorry for the slight (2days?) delay

been occupied by a huge branch re. the file-system browser and stuff. which in fact is already planted on master.

nevermind then

i'll get back soon
don't despair ;)

**Comment by schnitzeltony** [comment]
No problem - I think Xdir is worth spending time on it. Just looked at the code to get an idea - and yes I AM WATCHING YOU :)

Enjoy..

**Comment by rncbc** [comment]
ok.

after some closer look, it come to my that

qtractorMidiManager::deleteAudioOutputBus() is on called in a unsafe situation on qtractorMidiManager destructor--meaning "unsafe" like that it is not guarded by a qtractorSession::lock/unlock() sandwich;

this said, it should call for a PR re-treatment, perhaps?

byee

**Comment by schnitzeltony** [comment]
The method deleteAudioOutputBus is called at:

* qtractorMidiManager::~qtractorMidiManager: You mentioned that
* qtractorMidiManager::setAudioOutputBus (twice because it calls createAudioOutputBus)
* qtractorMidiManager::createAudioOutputBus

For adding plugins during MIDI import (still WIP - my recent PR) the code uses qtractorPluginList::loadElement for each track imported. That calls setAudioOutputBus and made me aware of this issue.

**Comment by schnitzeltony** [comment]
Off topic: Just saw, that you merged dir-view - also to neonx - Thanks!
Dir-view fits so nicely to what the MIDI extension is doing. Have get this done to get it to public...

**Comment by schnitzeltony** [comment]
Just saw you took care the standard - deferred way. Thanks. If you have some spare cycles and really nothing to do please merge that in neonx :)

**Comment by rncbc** [comment]
done. merged branch 'master' into 'neonx'.

**Pull request closed without merging**
